"""Add option to show/hide shuffle button

Revision ID: 03a325b68204
Revises: 1db782da653d
Create Date: 2021-11-19 12:21:57.029743

"""

# revision identifiers, used by Alembic.
revision = "03a325b68204"
down_revision = "1db782da653d"

from alembic import op
from sqlalchemy import orm
import sqlalchemy as sa
import oh_queue.models
from oh_queue.models import *


def upgrade():
    # Get alembic DB bind
    connection = op.get_bind()
    session = orm.Session(bind=connection)

    courses_using_shuffle = (
        session.query(TicketEvent.course)
        .filter_by(event_type=TicketEventType.shuffled)
        .distinct()
    )

    for course in session.query(ConfigEntry.course).distinct():
        enabled = course in courses_using_shuffle
        session.add(
            ConfigEntry(
                key="enable_shuffle",
                value="true" if enabled else "false",
                public=True,
                course=course[0],
            )
        )

    session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
