"""Make presence indicator toggleable

Revision ID: 1db782da653d
Revises: f0d77a64bc62
Create Date: 2021-09-08 11:34:38.144206

"""


# revision identifiers, used by Alembic.
revision = "1db782da653d"
down_revision = "f0d77a64bc62"

from sqlalchemy import orm
from alembic import op
import sqlalchemy as sa
import oh_queue.models
from oh_queue.models import *


def upgrade():
    # Get alembic DB bind
    connection = op.get_bind()
    session = orm.Session(bind=connection)

    for course in session.query(ConfigEntry.course).distinct():
        session.add(
            ConfigEntry(
                key="show_presence",
                value="true",
                public=True,
                course=course[0],
            )
        )

    session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
