"""add always show appointment join call

Revision ID: 2bc1ae0291d5
Revises: 80fed5bf8aa7
Create Date: 2022-01-30 22:53:23.202427

"""

# revision identifiers, used by Alembic.
revision = "2bc1ae0291d5"
down_revision = "80fed5bf8aa7"

from sqlalchemy import orm
from alembic import op
import sqlalchemy as sa
import oh_queue.models
from oh_queue.models import *


def upgrade():
    # Get alembic DB bind
    connection = op.get_bind()
    session = orm.Session(bind=connection)

    for course in session.query(ConfigEntry.course).distinct():
        session.add(
            ConfigEntry(
                key="always_show_appointment_join_call",
                value="false",
                public=True,
                course=course[0],
            )
        )

    session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
