"""Add ticket notification toggle

Revision ID: 3d327f052dac
Revises: 976c8a02f096
Create Date: 2022-03-15 15:39:27.747333

"""

# revision identifiers, used by Alembic.
revision = "3d327f052dac"
down_revision = "976c8a02f096"

from sqlalchemy import orm
from alembic import op
import sqlalchemy as sa
import oh_queue.models
from oh_queue.models import *


def upgrade():
    # Get alembic DB bind
    connection = op.get_bind()
    session = orm.Session(bind=connection)

    for course in session.query(ConfigEntry.course).distinct():
        session.add(
            ConfigEntry(
                key="send_ticket_notifications",
                value="true",
                public=True,
                course=course[0],
            )
        )

    session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
