"""add auto activate appointments

Revision ID: 80fed5bf8aa7
Revises: 03a325b68204
Create Date: 2022-01-17 13:55:31.239293

"""

# revision identifiers, used by Alembic.
revision = "80fed5bf8aa7"
down_revision = "03a325b68204"

from sqlalchemy import orm
from alembic import op
import sqlalchemy as sa
import oh_queue.models
from oh_queue.models import *


def upgrade():
    # Get alembic DB bind
    connection = op.get_bind()
    session = orm.Session(bind=connection)

    for course in session.query(ConfigEntry.course).distinct():
        session.add(
            ConfigEntry(
                key="auto_activate_appointments",
                value="false",
                public=True,
                course=course[0],
            )
        )
        session.add(
            ConfigEntry(
                key="auto_activate_appointments_frequency",
                value="12",
                public=True,
                course=course[0],
            )
        )
        session.add(
            ConfigEntry(
                key="auto_activate_appointments_range",
                value="12",
                public=True,
                course=course[0],
            )
        )

    session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
