"""Added private appointment logging

Revision ID: 976c8a02f096
Revises: 2bc1ae0291d5
Create Date: 2022-03-14 21:05:14.824018

"""

# revision identifiers, used by Alembic.
revision = "976c8a02f096"
down_revision = "2bc1ae0291d5"

from sqlalchemy import orm
from alembic import op
import sqlalchemy as sa
import oh_queue.models
from oh_queue.models import *


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "appointment", sa.Column("private_pinged", sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###

    # Get alembic DB bind
    connection = op.get_bind()
    session = orm.Session(bind=connection)

    for course in session.query(ConfigEntry.course).distinct():
        session.add(
            ConfigEntry(
                key="slack_notif_missed_appt_private",
                value="false",
                public=True,
                course=course[0],
            )
        )

    session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("appointment", "private_pinged")
    # ### end Alembic commands ###
