"""Add appointment prompt config

Revision ID: f0d77a64bc62
Revises: 11e366ca2e4f
Create Date: 2021-09-05 18:49:02.152767

"""

# revision identifiers, used by Alembic.
revision = "f0d77a64bc62"
down_revision = "11e366ca2e4f"

from sqlalchemy import orm
from alembic import op
import sqlalchemy as sa
import oh_queue.models
from oh_queue.models import *


def upgrade():
    # Get alembic DB bind
    connection = op.get_bind()
    session = orm.Session(bind=connection)

    for course in session.query(ConfigEntry.course).distinct():
        session.add(
            ConfigEntry(
                key="appointment_mode_title",
                value="Appointments",
                public=True,
                course=course[0],
            )
        )
        session.add(
            ConfigEntry(
                key="appointment_prompt",
                value="",
                public=True,
                course=course[0],
            )
        )

    session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
